stages:
  preprocess:
    cmd: python pipeline/preprocess/run.py --input_artifact_name pipeline/data/census.csv
      --output_artifact_name pipeline/data/preprocessing_data.csv
    deps:
    - pipeline/data/census.csv
    - pipeline/preprocess/run.py
    outs:
    - pipeline/data/preprocessing_data.csv
  datacheck:
    cmd: pytest pipeline/check_data -s -vv --sample_artifact pipeline/data/preprocessing_data.csv
      --param params.yaml
    deps:
    - pipeline/check_data/conftest.py
    - pipeline/check_data/test_data.py
    - pipeline/data/preprocessing_data.csv
    params:
    - data.ks_alpha
    - data.reference_dataset
  segregate:
    cmd: python pipeline/segregate/run.py --input_artifact pipeline/data/preprocessing_data.csv
      --param params.yaml
    deps:
    - pipeline/data/preprocessing_data.csv
    - pipeline/segregate/run.py
    params:
    - data.stratify
    - data.test_size
    - main.random_seed
    outs:
    - pipeline/data/test_data.csv
    - pipeline/data/train_data.csv
  train:
    cmd: python pipeline/train/run.py --train_data pipeline/data/train_data.csv --param
      params.yaml --score_file pipeline/data/train_scores.json
    deps:
    - pipeline/data/train_data.csv
    - pipeline/train/helper.py
    - pipeline/train/run.py
    - pipeline/train/transformer_feature.py
    params:
    - data.stratify
    - data.val_size
    - main.random_seed
    - train.export_artifact
    outs:
    - pipeline/data/encoder_export
    - pipeline/data/model_export
    metrics:
    - pipeline/data/train_scores.json:
        cache: false
  evaluate:
    cmd: python pipeline/evaluate/run.py --test_data pipeline/data/test_data.csv --model
      pipeline/data/model_export --encoder pipeline/data/encoder_export --score_file
      pipeline/data/test_scores.json --slice_file pipeline/data/slice_output.json
    deps:
    - pipeline/data/encoder_export
    - pipeline/data/model_export
    - pipeline/data/test_data.csv
    - pipeline/evaluate/run.py
    - pipeline/train/helper.py
    - pipeline/train/transformer_feature.py
    outs:
    - pipeline/data/slice_output.json
    metrics:
    - pipeline/data/test_scores.json:
        cache: false
