name: deploy
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy=1.21.5
  - uvicorn=0.17.5
  - gunicorn=20.1.0
  - requests=2.27.1
  - fastapi=0.74.0
  - scikit-learn=1.0.2
  - python=3.8
  - jupyterlab=3.2.9
  - jupyter=1.0.0
  - seaborn=0.11.2
  - pandas-profiling=3.1.0
  - ipywidgets=7.6.5
  - jupyterlab_widgets=1.0.2
  - git=2.34.1
  - flake8=4.0.1
  - black=22.1.0
  - pydantic=1.9.0
  - dvc=2.9.4
  - dvc-s3=2.9.4
  - wget=1.20.1
  - yaml=0.2.5
  - pip=21.3.1
  - pandas=1.3.5
  - pytest==6.2.5
  - autopep8=1.6.0
  - xgboost=1.5.1