main:
  # This seed will be used to seed the random number generator
  # to ensure repeatibility of the data splits and other
  # pseudo-random operations
  random_seed: 42
data:
  reference_dataset: "pipeline/01_data/preprocessing_data.csv"
  # Threshold for Kolomorov-Smirnov test
  ks_alpha: 0.05
  test_size: 0.3
  val_size: 0.3
  # Stratify according to the target when splitting the data
  # in train/test or in train/val
  stratify: "salary"
train:
  decision_tree:
    criterion: "entropy"
    splitter: "best"
    max_depth: 13
  numerical_pipe:
    model: 0
  export_artifact: "pipeline/01_data/model_export"
  export_encoder: "pipeline/01_data/encoder_export"